CREATE TABLE USERS (
	USER_ID INT NOT NULL AUTO_INCREMENT, 
	USERNAME VARCHAR(50) NOT NULL UNIQUE ,
	FIRST_NAME VARCHAR(25),
	LAST_NAME VARCHAR(25),
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	PHONE_NO VARCHAR(20),
	PASSWORD VARCHAR(255) NOT NULL,
	BANK_ACC_NO VARCHAR(35),
	CREDIT_CARD_NO VARCHAR(16),
	PROFILE_PIC VARCHAR(512),
	JOIN_DATE DATE,
	POINTS INT(6),
	PRIMARY KEY(USER_ID)
);

CREATE TABLE ADMIN ( 
	ADMIN_ID INT NOT NULL AUTO_INCREMENT, 
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	PHONE_NO VARCHAR(20),
	PASSWORD VARCHAR(255) NOT NULL,
	PRIMARY KEY(ADMIN_ID)
);

CREATE TABLE CITIES
(
	CITY_ID INT AUTO_INCREMENT,
	CITY_NAME VARCHAR(60) NOT NULL,
	PRIMARY KEY(CITY_ID)
);

CREATE TABLE ADDRESSES 
(
	ADDRESS_ID INT AUTO_INCREMENT,
	STREET VARCHAR(50) NOT NULL,
	POST_CODE VARCHAR(20) NOT NULL,
	CITY_ID INT NOT NULL,
	PRIMARY KEY(ADDRESS_ID),
	FOREIGN KEY(CITY_ID) REFERENCES CITIES(CITY_ID)
);
CREATE TABLE SHOPS
(
	SHOP_ID INT AUTO_INCREMENT PRIMARY KEY,
	ADMIN_ID INT NOT NULL,
	ADDRESS_ID INT NOT NULL UNIQUE,
	SHOP_NAME VARCHAR(20),
	FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
	FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID)
);
 
CREATE TABLE PRODUCT_UNIT
(
	UNIT_ID INT AUTO_INCREMENT PRIMARY KEY,
	UNIT_NAME VARCHAR(10) NOT NULL
);
 
CREATE TABLE PRODUCT_CATEGORY
(
	CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_NAME VARCHAR(50) NOT NULL
);
 
CREATE TABLE PRODUCTS
(
	PRODUCT_ID INT AUTO_INCREMENT NOT NULL,
	PRODUCT_NAME VARCHAR(60) NOT NULL,
	UNIT_ID INT NOT NULL,
	CATEGORY_ID INT NOT NULL,
	STOCK_QUANTITY INT,
	DESCRIPTION VARCHAR(255),
	PRODUCT_PRICE INT NOT NULL,
	OFFER_PCT INT,
	EXPIRE_DATE DATE,
	PRODUCT_RATING FLOAT,
	FOR_UNIT INT NOT NULL,
	PRIMARY KEY(PRODUCT_ID),
	FOREIGN KEY(UNIT_ID) REFERENCES PRODUCT_UNIT(UNIT_ID),
	FOREIGN KEY(CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(CATEGORY_ID)
);
 
CREATE TABLE PRODUCT_PHOTOS_PATH
(
    PRODUCT_ID INT NOT NULL,
    PATH VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);
 
CREATE TABLE PAYMENTS
(
	TRANSACTION_ID VARCHAR(50) PRIMARY KEY,
	TRANSACTION_DATE DATE DEFAULT(CURRENT_DATE) NOT NULL,
	AMOUNT INT NOT NULL,
	PAYMENT_METHOD VARCHAR(30)
);
 
CREATE TABLE DEPOSITS (
	USER_ID INT,
	TRANSACTION_ID VARCHAR(50) UNIQUE,
	BANK_ACC_NO VARCHAR(35),
	FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY(TRANSACTION_ID) REFERENCES PAYMENTS(TRANSACTION_ID)
);
 
CREATE TABLE CART
(
	CART_ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT NOT NULL,
	SHOP_ID INT NOT NULL,
	PRODUCTS_ID VARCHAR(255) NOT NULL,
	PRODUCTS_COUNT VARCHAR(255) NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY(SHOP_ID) REFERENCES SHOPS(SHOP_ID)
);
 
CREATE TABLE PRODUCT_ORDER
(
	ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
	CART_ID INT NOT NULL,
	TRANSACTION_ID VARCHAR(50) NOT NULL,
	SHOP_RATING FLOAT,
	FOREIGN KEY(CART_ID) REFERENCES CART(CART_ID),
	FOREIGN KEY(TRANSACTION_ID) REFERENCES PAYMENTS(TRANSACTION_ID)
);
CREATE TABLE PRODUCT_REVIEW
(
	REVIEW_ID INT AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_ID INT,
	REVIEW VARCHAR(255) NOT NULL,
	FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

